image: docker:dind

services: 
 - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  

build_vps:
  before_script:
   - docker info
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -t registry.slovendor.com/vps:latest --network=host . 
    - docker push registry.slovendor.com/vps:latest

build_db:
  before_script:
   - docker info
  script:
    - cd db
    - pwd
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -t registry.slovendor.com/db:latest --network=host . 
    - docker push registry.slovendor.com/db:latest

build_passthru:
  before_script:
   - docker info
  script:
    - cd passthru
    - pwd
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -f NginxDockerfile -t registry.slovendor.com/passthru:latest --network=host .
    - docker push registry.slovendor.com/passthru:latest


run_tests:
  script:
    - apk add python3 py3-pip
    - pip3 install mysql-connector-python flask pyyaml --break-system-packages
    - cd tests && python3 -m unittest tests.py