image: docker:dind

services: 
 - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive
  DIND_IMAGE: registry.slovendor.com/docker-py-ssh

before_script:
 - mkdir ~/.ssh
 - chmod 640 ~/.ssh
 - echo "$SSH_ID_RSA_PUB" >> ~/.ssh/id_rsa.pub
 - echo "$SSH_ID_RSA" >> ~/.ssh/id_rsa
 - chmod 640 ~/ssh/id_rsa.pub
 - chmod 400 ~/.ssh/id_rsa
 - echo -e "host *\n    StrictHostKeyChecking no" >> ~/.ssh/config
 - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
 - git submodule update --init --recursive
 - git submodule sync

build_vps:
  image: ${DIND_IMAGE}
  before_script:
   - docker info
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -t registry.slovendor.com/vps:latest --network=host . 
    - docker push registry.slovendor.com/vps:latest

build_db:
  before_script:
   - docker info
  script:
    - cd db
    - pwd
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -t registry.slovendor.com/db:latest --network=host . 
    - docker push registry.slovendor.com/db:latest

build_passthru:
  image: ${DIND_IMAGE}
  before_script:
   - docker info
  script:
    - cd passthru
    - pwd
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -f NginxDockerfile -t registry.slovendor.com/passthru:latest --network=host .
    - docker push registry.slovendor.com/passthru:latest

build_scheduler:
  image: ${DIND_IMAGE}
  before_script:
   - docker info
  script:
    - cd scheduler
    - pwd
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.slovendor.com
    - DOCKER_BUILDKIT=0 docker build -f Dockerfile -t registry.slovendor.com/scheduler:latest --network=host .
    - docker push registry.slovendor.com/scheduler:latest


