version: "3"

services:
  db:
    image: mysql:latest
    networks:
      vps:
        ipv4_address: 10.0.0.20
    ports:
     - "3306:3306"
    volumes:
     - "db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.slovendor.com/app
    container_name: app
    networks:
      vps:
        ipv4_address: 10.0.0.100
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - "${HERE}:/vps"
      - "${HERE}/log/:/var/log/"
    environment:
     - VPS_DB_HOST=10.0.0.20
     - VPS_SALT_FILE=${HERE}/.salt
     - SECRET_KEY=goatse
  passthru:
    image: registry.slovendor.com/passthru
    build:
      context: passthru
      network: host
      dockerfile: NginxDockerfile
    container_name: passthru
    networks:
      vps:
        ipv4_address: 10.0.0.10
    ports:
     - "443:443"
     - "80:80"
    expose:
      - 443
      - 80
    volumes:
     - "${HERE}/passthru:/vps"
    environment:
      - VPS_DB_HOST="10.0.0.20"
      - SECRET_KEY="theGoatman69"
      - VPS_SALT_FILE="/vps/.salt"
volumes:
  db:
    external: true

networks:
  vps:
    ipam:
      driver: default
      config:
       - subnet: "10.0.0.0/24"
         gateway: 10.0.0.1

