version: "3"

services:
  db:
    image: mysql:latest
    build:
      context: db
    networks:
      vps:
        ipv4_address: 10.0.0.20
    ports:
      - 3306:3306
    volumes:
     - "db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.slovendor.com/vps
    container_name: app
    networks:
      vps:
        ipv4_address: 10.0.0.100
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - "/vps:/vps"
      - "/var/log/:/var/log/"
    environment:
     - VPS_DB_HOST=10.0.0.20
     - VPS_SALT_FILE=/vps/.salt
     - SECRET_KEY=goatse

    
volumes:
  db:
    external: true

networks:
  vps:
    ipam:
      driver: default
      config:
       - subnet: "10.0.0.0/24"
         gateway: 10.0.0.1

