version: "3"

services:
  db:
    image: db
    container_name: db
    networks:
      vps:
        ipv4_address: 10.0.0.10
    ports:
     - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"
    restart: on-failure
    build:
      context: db
    environment:
     - MYSQL_ROOT_PASSWORD=123456

  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: app
    container_name: app
    networks:
      vps:
        ipv4_address: 10.0.0.100

    ports:
      - "8080:8080"
    restart: on-failure
  passthru:
    build:
      context: .
      dockerfile: passthru/NginxDockerfile
    image: passthru
    container_name: passthru
    networks:
      vps:
        ipv4_address: 10.0.0.20
    ports:
     - "443:443"
     - "80:80"
    expose:
      - 443
      - 80
volumes:
  db:
    external: true

networks:
  vps:
    ipam:
      driver: default
      config:
       - subnet: "10.0.0.0/24"
         gateway: 10.0.0.1

