
services:
  db:
    image: mysql:latest
    network_mode: host
    volumes:
     - "db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
  

volumes:
  db: 
    external: true

          

